### ISSUE TITLE
app.wm_attributes(„-transparent“, „green“)

### ISSUE THREAD

**Issue by not-nef** [sumeshir26/TimerX#15]
Hey There!

I am trying to run the script on macos 10.13.6 and on line 24 it throws me the following Error:

```
Traceback (most recent call last):
 File "/Users/***/Downloads/TimerX-master/main.py", line 24, in <module>
  app.wmattributes("-transparent", "green")
 File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 2005, in wm_attributes
  return self.tk.call(args)
_tkinter.TclError: expected boolean value but got "green"
```

When i delete that line, the application seems to run fine.

**Comment by im-coder-lg** [comment]
Maybe we need the hex code, @sumeshir26 let's test this in the morning.

**Comment by not-nef** [comment]
> Maybe we need the hex code, @sumeshir26 let's test this in the morning.

boolean means true or false right?

**Comment by im-coder-lg** [comment]
Ohh... I absolutely ignored that... But let's try a hex code in place of green, just to make sure.

**Comment by not-nef** [comment]
Ok, i found out, that this is because of the OS.

```
app.wm_attributes("-transparent", "green")
```
should absolutely work fine.

But for macos you have to do:
```
app.wm_attributes("-transparent", True)
app.config(bg="systemTransparent")
```

**Comment by sumeshir26** [comment]
@not-nef Okay, I will add that.

**Comment by im-coder-lg** [comment]
Imitating the platform code will be perfect for this.

**Comment by sumeshir26** [comment]
@not-nef I fixed this on your fork

**Comment by not-nef** [comment]
> @not-nef I fixed this on your fork

Thanks
