### ISSUE TITLE
Request to make a documentation/homepage site using SSGs

### ISSUE THREAD

**Issue by im-coder-lg** [sumeshir26/TimerX#23]
We could also use Jekyll that can use Vercel... Let's take Jekyll, that's widely supported and we will use Netlify for the website deployment since it has Netlify CMS that could allow us to edit without going to GitHub.

_Originally posted by @im-coder-lg in https://github.com/sumeshir26/TimerX/issues/21#issuecomment-1000204245_

In another project called Xplorer(it's best to quote this here so that it might help), they use a NodeJS framework called Docusaurus.
SSGs I know:
1. CODEDOC(stands out for documentation and its special Markdown syntax but doesn't work on Netlify, Vercel, etc.)
2. Jekyll(blogs, websites, too much JavaScript)
3. Next.js(too static but fast as lightning)
4. Docusaurus(never tried this from scratch)

Any ideas on other SSGs? No Gatsby since that seems too complex. The font is kinda bad too(no offence gatsby, I like Montserrat).

**Comment by im-coder-lg** [comment]
Which one can we use for the website? We have Vercel as deployment+hoster, Netlify as a solid alternative if we use their CMS, and GitHub Pages(no PR preview like Vercel `:(`) too.

**Comment by im-coder-lg** [comment]
I'm assigning this to myself since I am kind of an expert when it comes to this.

**Comment by im-coder-lg** [comment]
Documentation: https://pmarsceill.github.io/just-the-docs/

Homepage... Let's use CODEDOC, I told you above that it has a special Markdown syntax for it and using that, we could make users see Light mode and Dark Mode of TimerX, all with a click of a button.
It's smooth too.

**Comment by im-coder-lg** [comment]
Started development: [`website`](https://github.com/im-coder-lg/TimerX-fork/tree/website).

**Comment by sumeshir26** [comment]
Okay, tell me when its done

**Comment by sumeshir26** [comment]
How do I test this? Is this on vercel?

**Comment by im-coder-lg** [comment]
> How do I test this? Is this on vercel?

Not yet. I need to configure the websites, add theming to CODEDOC so that it doesn't look too alien, check the JTD theme, but I will make a PR after I succeed on them. PS: It _will_ have a lot of commits.

**Comment by im-coder-lg** [comment]
Right now, here's what I've accomplished:
- Get JTD and CODEDOC(boilerplate, need to configure better)
- Modify it a bit(extensive modifications in CODEDOC part_

What I must do soon:
- [ ] Master it
- [ ] Get syntax
- [ ] Make sure front matter is top-notch
- [ ] Configure TOC on CODEDOC sidebar(button replacing needed)
- [ ] Add some more configuration, test on Vercel
- [ ] Deploy!
