### ISSUE TITLE
Vercel deployment request(now Netlify)

### ISSUE THREAD

**Issue by im-coder-lg** [sumeshir26/TimerX#35]
I thought we were going to open Vercel deploys yesterday, is it done? If not, tell me here and I'll help out with the creation.

**Comment by sumeshir26** [comment]
@im-coder-lg No, my github account is just not linking!

**Comment by im-coder-lg** [comment]
Sign up with an email and then try GitHub linking.

**Comment by im-coder-lg** [comment]
Or try signing up from other devices than your PC.

**Comment by im-coder-lg** [comment]
My login worked, maybe it's your network, the ping extended. Try using mobile hotspots or any fast network.

**Comment by sumeshir26** [comment]
Did it ask you to put in a phone number?

**Comment by im-coder-lg** [comment]
Nah.

**Comment by im-coder-lg** [comment]
I just signed up with GitHub. Maybe that's a new safety feature, it'd try setting MFA codes, but _you_ try with GitHub on a mobile or any other computer.

**Comment by im-coder-lg** [comment]
Alright, new guide!
1. Go to https://vercel.com/signup/email? and enter any email of yours. DO NOT CLOSE THAT TAB.
2. They'll send an email. Go to your inbox and open that. Click the button they give.
3. You'll get a popup that you are logged in, go to that signup tab and link your GitHub.
4. Et voilà! You are on your Vercel. THis made me create another account too, but remember, there ain't passwords, it's login links.

**Comment by im-coder-lg** [comment]
Wait, are you using other services than Vercel? It didn't ask me any phone numbers. Don't Google the link, use the one I gave.

**Comment by sumeshir26** [comment]
I always get this error:
![image](https://user-images.githubusercontent.com/68823982/148522692-462f7e19-33a8-4a59-b813-64ca6244a660.png)

**Comment by im-coder-lg** [comment]
Whoa. Vercel didn't ask me any phone numbers. Have you tried waiting?

**Comment by im-coder-lg** [comment]
Have you tried all the mobile numbers at your home? I don't think Vercel ever needs phone numbers. It didn't ask me at all.

**Comment by im-coder-lg** [comment]
I think this might be with ProtonMail(check your image's URL). I signed up with one(yeah it's true I do have a ProtonMail) and it didn't ask me anything. Do you have VPNs? If not, try this:
On your PC, try signing up and authenticate from your mobile, it might work.

**Comment by im-coder-lg** [comment]
Well, now it did lol. Vercel requested my phone number.

**Comment by im-coder-lg** [comment]
I am in my dupe account now.
My OTP worked man, but for that I can't give my phone number.

**Comment by im-coder-lg** [comment]
@sumeshir26 does anyone in your family have a Vercel account? It could be that they registered the mobile number to them right? Have you checked Netlify too?

**Comment by im-coder-lg** [comment]
Wait. Let's go back the history track. When I used a Vivaldi Webmail account, it didn't ask me anything but when I used _ProtonMail_, it asked. So it might be the email. Try making a Vivaldi account. It will ask you for a mobile number but my signup worked in a few seconds. It _has_ to be the email that causes the problem.

**Comment by sumeshir26** [comment]
Il try using neltify

**Comment by im-coder-lg** [comment]
Problem is, Netlyify has a 100 GB of bandwidth. IDK if it's enough.

**Comment by im-coder-lg** [comment]
@sumeshir26 does Netlify work?

**Comment by sumeshir26** [comment]
Doing that now

**Comment by im-coder-lg** [comment]
Also, I am finding how to enable PR deployment previews. That can help us see a preview of the website in the person's PR. Vercel does it better, that's why I asked you for checking Vercel.

**Comment by im-coder-lg** [comment]
Make sure [this](https://docs.netlify.com/configure-builds/repo-permissions-linking/#authentication-with-the-netlify-github-app) is done, so that [this](https://docs.netlify.com/site-deploys/deploy-previews/) can work.

**Comment by im-coder-lg** [comment]
Additionally(I said _additionally_, so please remember that), you could grant me access to the Netlify team, it always creates one at startup, so if you want, you could add me and I might be able to help you on deploy errors. They always redirect back to Netlify.

**Comment by sumeshir26** [comment]
> you could grant me access to the Netlify team
@im-coder-lg Thats exactly what I was going to ask you because the build succeeds but it does not work.

**Comment by im-coder-lg** [comment]
Well, head to the Members tab, and add my Protonmail. Same username without dashes(`imcoderlg`).

**Comment by sumeshir26** [comment]
Now, its asking me for either money or an open source account, applying for one

**Comment by im-coder-lg** [comment]
Woah. Let _me_ see that!

**Comment by im-coder-lg** [comment]
I'll invite you to my team, just to see that. PS: I know the email, it's on your screenshot.

**Comment by im-coder-lg** [comment]
Well, it's true. You _do_ need to pay. Try Vercel again.

**Comment by im-coder-lg** [comment]
This time, DO NOT USE your ProtonMail. Go to [`vivaldi.net`](https://vivaldi.net) and sign up. Give a mobile number, it will authenticate and then head to [`https://webmail.vivaldi.net`](https://webmail.vivaldi.net) and log in to your Vivaldi account. THen use that same email to log in. It _will_ work.

**Comment by im-coder-lg** [comment]
I see that you installed Netlify. Go to Settings > Build and deploy and edit the Build settings. Change the build directory to `docs`. Make sure deploy logs are public so that I can inspect them. I will have to test some things from my end, so wait for my next reply, I need to fix deployment.

**Comment by im-coder-lg** [comment]
Also, two things:
1. Merge #41 
2. Allow reviewer access for me.
That's all for now.

**Comment by sumeshir26** [comment]
What do you mean?

**Comment by im-coder-lg** [comment]
I need the URL, and I sent a permission from my Netlify to yours for joining as a reviewer. PS: It's free and unlimited.

**Comment by im-coder-lg** [comment]
No worries, found the URL: https://timerx-app.netlify.app

**Comment by sumeshir26** [comment]
Yay!

**Comment by im-coder-lg** [comment]
Also, about the reviewer access, did you receive it?

**Comment by im-coder-lg** [comment]
Check this: https://github.com/sumeshir26/TimerX/pull/41#issuecomment-1007941733
