### ISSUE TITLE
Get rid of unneccesary files

### ISSUE THREAD

**Issue by sumeshir26** [sumeshir26/TimerX#7]
### Discussed in https://github.com/sumeshir26/TimerX/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **not-nef** December  3, 2021</sup>
@sumeshir26 you should remove some unneccesary files and dirs like the .spec files, __pycache__ or .vscode imo</div>

**Comment by sumeshir26** [comment]
@not-nef Hi, about those files, when I first created this project, it did not have a gitignore. So, those files stayed. I will delete those soon

**Comment by im-coder-lg** [comment]
Please exclude the .spec file, we need it for the builds.

**Comment by not-nef** [comment]
there is a file called help.spec but no help.py, so what is it for?

**Comment by im-coder-lg** [comment]
idk, will check that soon.

**Comment by im-coder-lg** [comment]
I think it generates a strange help file. I will inspect that later.
